# Rime default settings
# encoding: utf-8
# CC-BY-4.0

config_version: '0.40'

schema_list:
  - schema: PY_c					# 拼音++
  # - schema: easy_en				# 英文
  # - schema: numbers				# 数字
  # - schema: pinyin_simp			# 简体拼音
  - schema: tiger					# 虎字·官方
  # - schema: tiger_chord_popping		# 虎字·并击
  - schema: tiger_code				# 虎字·官方
  # - schema: tiger_code_52p			# 虎字·五顶二
  # - schema: tiger_code_53p			# 虎字·五顶三
  - schema: tiger_codes			# 虎词·官方
  - schema: tiger_oni				# 虎码·鬼虎
  - schema: tiger_phrase			# 虎字·句
  # - schema: tiger_phrase_chord		# 虎字·并击
  - schema: tiger_phrases			# 虎词·句
  - schema: tigress				# 虎词·官方
  - schema: wubi06				# 五笔06版
  # - schema: wubi06_pinyin			# 五笔06版·拼音混输
  # - schema: wubi06_trad				# 五笔06版·简入繁出·拼音混输
  - schema: wubi86_jidian			# 极点五笔86版
  # - schema: wubi86_jidian_pinyin		# 极点五笔86版·拼音混输
  # - schema: wubi86_jidian_trad		# 极点五笔86版·简入繁出
  # - schema: wubi86_jidian_trad_pinyin	# 极点五笔86版·简入繁出·拼音混输
  # - schema: wubi98_U				# 五笔98版·大字集
  - schema: wubi98_ci				# 五笔98版·词
  # - schema: wubi98_dz				# 五笔98版·字


switcher:
  caption: "〔设置〕"
  hotkeys:
    - "Control+grave"
    - "Control+F8"
    - F4
  save_options:
    - full_shape
    - ascii_punct
    - traditionalization
    - emoji
    - extended_char
    - mars
    - prediction
    - tiger_spelling.off
    - tiger_spelling.lv1
    - tiger_spelling.lv2
    - tiger_spelling.lv3
    - tiger_spelling.lv4
    
    - simplification
    - extended_charset
    - zh_hant
    - zh_hans
    - zh_hant_tw
  fold_options: true
  abbreviate_options: true
  option_list_separator: '／'

menu:
  #alternative_select_labels: [ ⑴, ⑵, ⑶, ⑷, ⑸, ⑹, ⑺, ⑻, ⑼, ⑽ ]
  #alternative_select_labels: [ 〡, 〢, 〣, 〤, 〥, 〦, 〧, 〨, 〩, 〸 ]
  #alternative_select_labels: [ α, β, γ, δ, ε, ζ, η, θ, ι, κ ]
  page_size: 7

punctuator:
  __include: tiger:/punctuator

key_binder:
  import_preset: default
  bindings:
    __patch:
      - tiger:/keys/emacs_mode
      - tiger:/keys/tab
      - tiger:/keys/page_up_down
      #- tiger:/keys/selector
      - tiger:/keys/options_toggle
      
      - key_bindings:/emacs_editing
      - key_bindings:/move_by_word_with_tab
      - key_bindings:/paging_with_minus_equal
      - key_bindings:/paging_with_comma_period
      - key_bindings:/numbered_mode_switch


recognizer:
  patterns:
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$|^[a-z]+[.].+$"

ascii_composer:
  good_old_caps_lock: true
  switch_key:
    Caps_Lock: noop
    Control_L: noop
    Control_R: noop
    Eisu_toggle: clear
    Shift_L: commit_code
    Shift_R: commit_text
